export const AppStrings = {
    USERNAME_EXISTS: "username is already exist.",
    EMAIL_EXISTS: "Email is already registered.",
    MOBILE_EXISTS: "Mobile No is already exist.",
    MOBILE_IS_NOT_VALID: "Mobile No is not valid",
    USERNAME_NOT_EXISTS: "username does not exist.",
    EMAIL_NOT_EXISTS: "Email does not exist.",
    MOBILE_NOT_EXISTS: "Mobile does not exist.",
    INVALID_PASSWORD: "Your password is incorrect",
    BLACKLISTED_TOKEN: "blacklisted token.",
    INVALID_SESSION: "Your session is not valid.",
    INVALID_REQUEST: "Invalid request.",
    UNAUTHORIZED: "Full authentication is required to access this resource",
    INVALID_PAYLOAD: "Couldn't process data",
    USERNAME_EMAIL_MOBILE_REQUIRED: "username, email or mobile is required.",
    EMAIL_MOBILE_REQUIRED: "email or mobile is required.",
    OTP_SENT: "OTP sent successfully.",
    USER_CREDENTIAL_DOES_NOT_MATCH: "User credentials do not match.",
    DECRYPT_DATA_IS_REQUIRED: "Decrypt data is required.",
    CHECK_MAIL: "Check mail for OTP.",
    CHECK_PHONE: "Check phone for OTP.",
    INVALID_REASON: "Invalid reason type.",
    ALREADY_ADDED_REFERENCE: "Already added reference",
    USER_PROFILE_COMPLETED: "user profile register successfully",
    SOMETHING_WENT_WRONG: "Something went wrong",
    STATUS_UPDATED_SUCCESSFULLY: "Status update Successfully",
    REFERENCES_ADDED_SUCCESSFULLY: "References added Successfully",
    DOCUMENT_SUBMITTED_SUCCESSFULLY: "Document submitted Successfully",
    TERMINATE_ANOTHER_MOBILE_SESSION: "another session is used by other device",
    ALREADY_REGISTER:"You have already register with email",
    ALREADY_REGISTER_MOBILE:"You have already register with mobile",

    OTP_TOKEN_REQUIRED: "OTP and token is required.",
    INVALID_OTP: "Invalid OTP.",
    INVALID_DEVICE: "Invalid device.",
    OTP_EXPIRED: "OTP expired.",
    OTP_VERIFIED: "OTP verified.",
    OTP_NOT_MATCH: "OTP does not match.",
    OTP_ALREADY_VERIFIED: "OTP already verified.",
    OTP_REQUEST_LIMIT: "OTP request limit reached.",

    USER_NOT_FOUND: "User not found.",
    INVALID_TOKEN: "Invalid token.",
    TOKEN_EXPIRED: "Token expired.",

    SET_LOCATION: "Location not found.",

    PASSWORD_CHANGED: "Password changed successfully.",
    USERID_MISSING: "UserId is missing.",
    INCORRECT_OTP: "InCorrect OTP",
    USER_TYPE_MISMATCH: "User type mismatch.",

    PROVIDER_TYPE_MISSING_OR_INVALID: "Provider type is missing or invalid.",
    USER_NOT_PROVIDER: "User is not a provider.",
    USER_NOT_SEEKER: "User is not a seeker.",
    PROFILE_UPDATED: "Profile updated successfully.",
    SEEKER_INTRO_UPDATED: "Seeker intro updated successfully.",
    SEEKER_INTRO_SAVED: "Seeker intro saved successfully.",
    USER_DOES_NOT_MATCH: "User type does not match.",

    IMAGE_UPLOADED: "Image uploaded successfully.",
    IMAGE_NOT_FOUND: "Image not found.",
    IMAGE_NOT_UPLOADED: "Image not uploaded.",
    FILE_NOT_UPLOADED: "File not uploaded.",
    FILE_NOT_FOUND: "File not found.",
    VIDEO_NOT_UPLOADED: "Video not uploaded.",
    VIDEO_NOT_FOUND: "Video not found.",

    AUDIO_NOT_FOUND: "Audio not found.",
    AUDIO_NOT_UPLOADED: "Audio not uploaded.",
    AUDIO_UPLOADED: "Audio uploaded successfully.",

    PROFILE_FETCHED: "Profile fetched successfully.",

    SEEKER_ID_MISSING: "Seeker id is missing.",
    USER_MUST_BE_PROVIDER_OR_SEEKER: "User must be a provider or seeker.",


    JOB_POSTED_SUCCESSFULLY: "Job posted successfully.",
    JOB_NOT_FOUND: "Job not found.",
    JOB_NOT_FOUND_WITH_SEEKER: "Job not found with this seeker.",

    JOB_ID_REQUIRED: "Job id is required.",
    JOB_TIME_INVALID: "Job time is invalid.",
    JOB_APPLIED_SUCCESSFULLY: "Job applied successfully.",
    JOB_APPLIED_ALREADY: "Job applied already.",
    JOB_APPLIED_ALREADY_FOR_SAME_TIME: "another job is applied by you for same time.",
    JOB_NOT_OPEN: "Job is not open.",
    JOB_FINAL_AMOUNT_IS_INCORRECT: "Job final amount is incorrect",

    JOB_APPLIED_ALREADY_OR_SEEKER_ALREDY_REQUESTED: "Job applied already or seeker already requested.",
    SEEKER_ALREDY_REQUESTED: "Seeker already requested for this job.",
    JOB_NOT_ASSIGNED: "this job is not assigned to you.",

    ALREADY_APPLIED_FOR_THIS_JOB: "You have already applied for this job.",
    JOB_EXPIRED: "Job expired.",
    JOB_ASSIGNED_SUCCESSFULLY: "Job assigned successfully.",
    JOB_NOT_ASSIGNED_TO_PROVIDER: "Job is not assigned to provider.",

    APPLICANT_ID_REQUIRED: "Applicant id is required or not valid.",
    ACTION_REQUIRED: "Action is required or not valid.",
    JOB_STATUS_UPDATED_SUCCESSFULLY: "Job status updated successfully.",
    JOB_CANCELLED_SUCCESFULLY: "Job cancelled successfully.",
    JOB_ACTION_TIME_EXPIRE: "Job action time expire.",

    INVALID_LIST_TYPE: "Invalid list type.",
    INVALID_DETAIL_TYPE: "Invalid details type.",
    RATING_SUCCESSFULLY_SENT: "Rating successfully sent.",
    ALREADY_RATED: "You have already rated this field.",

    RATING_NOT_FOUND: "Rating not found.",
    NOT_AUTHORIZED: "You are not authorized to perform this action.",
    RATING_UPDATED_SUCCESSFULLY: "Rating updated successfully.",

    DISPUTE_SUCCESS: "Dispute successfully raised.",
    ALREADY_DISPUTED: "You have already disputed this field.",
    NO_JOB_ASSIGNED_WITH_THIS_ID: "No job assigned with this id.",
    DISPUTE_NOT_FOUND: "Dispute not found.",
    DISPUTE_ID_REQUIRED: "Dispute id is required.",

    USER_NOT_ELIGIBLE_TO_APPLY_JOB: "You are not eligible to apply for this job.",
    USER_NOT_ELIGIBLE_FOR_HIRING: "You are not eligible for hire to this job.",

    STATUS_NOT_ALLOWED: "Status not allowed to be updated.",
    JOB_REQUIREMENT_IS_FULFILLED: "Job requirement is fulfilled.",
    JOB_START_TIME_INVALID: "Job start time is must be greater than current time.",
    JOB_IS_NOT_AVAILABLE_FOR_HIRING: "Job is not available for hiring.",

    WALLET_CREATED: "Wallet created successfully.",
    WALLET_ALREADY_EXIST: "Wallet already exist.",
    WALLET_NOT_EXIST: "Wallet does not exist.",
    WALLET_BALANCE_IS_INSUFFICIENT: "You don't have enough balance to pay admin fees,Please add money in your wallet.",
    AMOUNT_MISSING: "Amount is missing.",
    WALLET_CAN_NOT_INTEGRETED: "Wallet can not integreated this time",

    SERVER_ERROR: "Server error. Please try again later.",
    RAZORPAY_ERROR: "Razorpay error. Please try again later.",

    AGE_NOT_VALID: "Age must be greater than 15.",
    DOB_NOT_VALID: "DOB must be greater than 15 years ago.",

    EMAIL_REQUIRED: "email is required.",
    ADMIN_NOT_FOUND: "user is not admin",
    ADMIN_DELETE: "admin is delete successfully",
    NOT_ACTIVE: "Admin is not active",

    ADMINID_MISSING: "AdminId is missing.",
    ADMIN_DOES_NOT_MATCH: "Admin role does not match.",

    REGISTER_SUCCESS: "Register Successfully.",
    ADMIN_LOGIN: "Admin Login Successfully.",
    LOGOUT_SUCCESS: "Logout Successfully.",
    SUCCESS: "Submit Successfully.",
    UPDATE: "Update Successfully.",
    DELETE: "Delete Successfully.",
    REFERAL_CODE_ALREADY_EXISTS: "Already Use This Code.",
    REFERAL_CODE_NOT_FOUND: "Not Found.",
    ALREADY_CREATED: "This User Already Created Referal Code.",

    ADMINID_INVALID: "Admin_id is invalid.",
    CONTACT_SUBMITED: "Contact form submitted successfully.",
    SUPER_ADMIN_ALREADY_EXISTS: "Super admin already exists.",

    WALLET_OLD_PIN_INVALID: "Invalid old pin.",
    PIN_ALREADY_SET: "Pin already set.",
    WALLET_NOT_FOUND: "Wallet not found.",
    WALLET_PIN_INVALID: "Invalid pin.",

    WALLET_SYNCHRONIZE_PIN_INVALID: "Synchronize pin is required or invalid",
    POLICY_CREATED: "policy created successfully",
    POLICY_UPDATED: "policy updated successfully",

    USER_NOT_VERIFIED: "User is not verified.",

    BUSINESSID_MISSING : "Business Id is missing",
    BUSINESS_NOT_FOUND : "Business is not found",
    
    USER_ALREADY_REQUESTED : "user already requested recipient",
    RECIPIENT_ALREADY_REQUESTED : "recipient already requested user",
    REQUEST_APPROVED : "Request approved",
    REQUEST_REJECTED : "Request rejeceted",
    REQUEST_SENT : "Request sent",
    ASSIGNED_WITH_OTHER_STATUS : "request assign with other status",

    MOBILE_SHOULD_BE_UNIQUE : "Mobile should be unique",
    EMAIL_SHOULD_BE_UNIQUE : "Email should be unique",
    INVALID_DATA : "Invalid data",


    NOT_TRUSTED:  "Not Trusted",
    AVG_TRUSTED : "Average Trusted",
    NOT_VERIFIED: "Not Verfied",
    ABOVE_AVERAGE_TRUST : "Above Average Trusted",
    ALMOST_TRUST :"Almost Trusted",
    SUPER_TRUSTED :"Super Trusted",
}